### ISSUE TITLE
GUI encounters error upon application of displacements

### ISSUE THREAD

**Issue by LJruns** [FranckLab/DVC-Simulator#1]
The following is the error that is returned immediately upon selection of a displacement in U1 with the radio button. The image stack I am using for input is 256x256x96 voxels. Is there a readily apparent user error that may be occuring? I followed the steps as delineated in the readme through step 3. I have not resized but I am unable to find a method of selecting displacement sizes. U2 and U3 displacements give similar errors as does the Update button.

Reference to non-existent field 'm'.

Error in DVC_simulator>displ1_Callback (line 1347)
m = handles.m;

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DVC_simulator (line 54)
    gui_mainfcn(gui_State, varargin{:});

Error in @(hObject,eventdata)DVC_simulator('displ1_Callback',hObject,eventdata,guidata(hObject))

Error while evaluating UIControl Callback

**Comment by mohakpatel** [comment]
A new version of the code has been released to solve GUI and other issues in the code. Can you please try the new code, and see if it works? Let us know if you have any issues. 

Cheers,
Mohak

Graduate Student
Franck Lab

**Comment by LJruns** [comment]
Thank you Mohak,

I tried running it on both the example stacks and my own images and wound
up getting errors both times. I think that it's probably something on my
end. I am running MATLAB 2015a if that might be a cause for trouble. I have
the image files in the same folder (they load without trouble). The way I
have been interpreting the procedure is as follows:
1. Run the GUI by using the command DVC_simulator in the command window.
2. Hit the "Load Image" button. Image appears in the GUI upon selection.
3. Select an axis for deformation application. This is where the errors
   seem to occur. Is there an intermediate step I am missing? Also, how does
   one update the subset size and spacing?

Thank you for your help!

Joe Heebner

On Thu, Oct 29, 2015 at 6:45 PM, Mohak Patel notifications@github.com
wrote:

> A new version of the code has been released to solve GUI and other issues
> in the code. Can you please try the new code, and see if it works? Let us
> know if you have any issues.
> 
> Cheers,
> Mohak
> 
> Graduate Student
> Franck Lab
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FranckLab/DVC-Simulator/issues/1#issuecomment-152348710
> .

## 

Joe Heebner
Case Western Reserve University
MS Class of 2015
Mechanical Engineering

**Comment by mohakpatel** [comment]
Hi Joe, 

I checked the codes again. I have been able to run the DVC-simulator with Matlab 2015a on my Windows 10 and Windows 7 PC. I'm not sure what issues you are facing.

The steps that I followed are:
1. Run the GUI by using the command DVC_simulator in the command window.
2. Hit the "Load Image" button. Image appears in the GUI upon selection
3. Select the subset size and spacing (I left them at their default values)
4. Select applied strain, translation, and strain type (I left them at their default values)
5. Hit Go
6. Results pop out. You can now select u1, u2, u3 or |u| to see quantities being plot. 

My GUI looks likes this:

![capture](https://cloud.githubusercontent.com/assets/12297377/10861983/3c562b88-7f6c-11e5-851a-8f7ff566c545.PNG)

Let me know if you can run the code by following these steps. And it should, as I have been able to run the same code today.

**Comment by mohakpatel** [comment]
Hi Joe, 
I was wondering if the last suggestion was helpful?

**Comment by LJruns** [comment]
Thanks Mohak,

It is very helpful. My GUI appears as follows:

[image: Inline image 2]
So I know the issue is that I missing several buttons from the top. I am
trying to get the 'guide DVC_simulator.fig' command to show them right now.
I will let you know when I get it running. Thanks again!

On Thu, Nov 5, 2015 at 1:55 AM, Mohak Patel notifications@github.com
wrote:

> Hi Joe,
> I was wondering if the last suggestion was helpful?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FranckLab/DVC-Simulator/issues/1#issuecomment-153973151
> .

## 

Joe Heebner
Case Western Reserve University
MS Class of 2015
Mechanical Engineering
(609)-571-2386

**Comment by LJruns** [comment]
Hello Mohak,

I got it running. Just needed to select all in the guide and shift the
buttons downward. I got good output from the example reduced stack. My
Image seems to be throwing a contour not rendered error though.

"Warning: Contour not rendered for non-finite ZData

> In contourfHGUsingMATLABClasses (line 43)
>   In contourf (line 54)
>   In DVC_simulator>pushbutton10_Callback (line 483)
>   In gui_mainfcn (line 95)
>   In DVC_simulator (line 54)
>   In
> @(hObject,eventdata)DVC_simulator('pushbutton10_Callback',hObject,eventdata,guidata(hObject))

Could this be because of too large an image to run? I am using 256x256x96
right now but I can crop to 96x96x96 if needed.

Thanks again for all your help!

-- Joe Heebner

**Comment by mohakpatel** [comment]
That's a weird error. Can you send your images, so that I can have a look at them?

Also, good work on the GUI. That's the only way it seems to work. We have tried different things on the GUI, but it doesn't always show up the same on different computers.

**Comment by LJruns** [comment]
Thanks Mohak,

It might not be a bad idea to squeeze a jpeg into the project files so
people have something to pattern off of. One of my images file is attached.
It was 32 voxels deep so I concatenated it twice onto itself. Let me know
if you get the same error. Thanks for the help!!

-Joe

**Comment by mohakpatel** [comment]
The image didn't come through. Can you give me a google drive or dropbox link to the file?

**Comment by LJruns** [comment]
Here is a dropbox link:
https://www.dropbox.com/s/47cl61owi4eaysy/Testforgoodness.mat?dl=0

Thanks for the quick response!!

On Sat, Nov 7, 2015 at 4:52 PM, Mohak Patel notifications@github.com
wrote:

> The image didn't come through. Can you give me a google drive or dropbox
> link to the file?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FranckLab/DVC-Simulator/issues/1#issuecomment-154756649
> .

## 

Joe Heebner
Case Western Reserve University
MS Class of 2015
Mechanical Engineering
(609)-571-2386

**Comment by mohakpatel** [comment]
Hi Joe, 

After some digging through we have figured out the issue. The short answer is that speckle pattern in your images aren't good enough for the DVC algorithm to track displacement. Hence, you are not getting any results. 

Longer answer: DVC tracks the displacement basically from finding the peak of cross-correlation in your images. For this, you need a good speckle pattern. In absence of a good speckle pattern, DVC can't find a cross-correlation and spits out NaNs. Thus you are seeing errors when you are using DVC-simulator in your images. 

Unfortunately, you won't be able to use DVC with your current images. You will need to optimize the speckle pattern in your images. Use DVC simulator see when you have the right speckle pattern in your images. 

Let me know if you have any questions. 

Best,
Mohak

**Comment by LJruns** [comment]
Hmm... Do you think it would work if we used the same sample but over fewer
voxels and used the black spots as our speckle? I also have another set of
images that might be more workable. I'll try to compile that into a 3D
volume and run it through the simulator.

**Comment by mohakpatel** [comment]
That approach will not work. Digital volume correlation techniques find displacements by tracking speckle pattern through correlation. For this speckle pattern need to be uniform and the size of each speckle spots need to be smaller than the subset size. This is different from particle tracker where you are trying to track a single spot. 

Here is a nice reference on speckle pattern quality: http://www.sciencedirect.com/science/article/pii/S0143816613001103

I'm not sure if this can be done with your samples, but an easy way to produce speckle pattern for volumetric images is by inserting beads in your samples. 

I hope this helps.
