### ISSUE TITLE
data format

### ISSUE THREAD

**Issue by yclu1214** [FranckLab/DVC-Simulator#2]
Hi,
I am a little bit confused about the data format.
What do you mean the intensity values at x, y, z positions?
My data store the x,y,z coordinate of each point with time.
Is it correct?
Thanks.

**Comment by mohakpatel** [comment]
DVC-Simulator checks if the speckle pattern in the image is good enough for DVC. Hence, the only single volumetric image for a particular time point is needed. Pick up the volume image for a particular time point and save it as a 3D Matlab matrix. 
Check the data structure in example data to see how your images need to look. Here is the link for [example data](https://drive.google.com/drive/u/0/folders/0ByhZqlrbo5srUDI5clRCM3VCX3M).
