### ISSUE TITLE
Simulator Graphs

### ISSUE THREAD

**Issue by mccartya** [FranckLab/DVC-Simulator#3]
Hello!  What does each axis represent on the bottom half of the results screen after running "DVC_simulator?"  I have some speckled images which I believe may not have adequate intensity, but am having trouble interpreting the results.  I have also attached a screenshot of the results after running the simulator on one of my stacks.  Thank you for your help!

![image](https://user-images.githubusercontent.com/35498682/35000055-ff86f93e-faa8-11e7-82cc-ad6837f44bbc.png)

**Comment by jrsmartin** [comment]
I also have a question about this -- what do the graphs exactly mean and what is generally considered an "acceptable" amount of error to still achieve accurate results? Thanks!

**Comment by FranckLab** [comment]
Apologies for taking a few days to respond and please feel free to respond again with any questions. In answer to @mccartya, the bottom half of shows histograms of percent recover error, 
$u_{error} = \frac{u_i - u_{imposed}}{u_{imposed}} \mtimes 100$ in each of the coordinate directions, for each displacement test case. One option I might suggest before reading too much into the results you see is to crop to just the regions that have your speckle pattern. Currently, it looks like the error is dominated by the blank regions in your image.  

@jrsmartin: Hopefully I've explained enough to roughly answer your first question.  More detail is available in the referenced paper (Estrada and Franck 2015, see the readme) that I will email you directly.  The acceptable error level very much depends on the application, so without knowing any details of what you are trying to do with the results I would hesitate to make any specific recommendations. I look for a roughly Gaussian distribution about a zero mean in general.

**Comment by ALandauer** [comment]
Since no additional comments and/or questions have arisen I am closing this thread.  If you do have further questions please don't hesitate to let us know.
